### PR TITLE
fix: bug regex fails on trailing dashes

### LINKED ISSUE #4: Bug - Regex fails on trailing dashes
Hey thanks for taking the time to review this issue. When using the plugin v0.0.2 I run into an error when searching with a trailing hyphens. Example when searching "co-workers" or even the word "co-":

```
Invalid regular expression: /co\-worker/giu: Invalid escape
```

Here is the code causing the problem:

```js
 const getRegex = (s, disableRegex, caseSensitive) => {
   return RegExp(disableRegex ? s.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&") : s, caseSensitive ? "gu" : "gui");
 };
```

---

Edited to better explain the issue

### PR DESCRIPTION
**Pull request by sereneinserenade**
closes #4

### CODE REVIEW

File: src/searchAndReplace.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ interface TextNodesWithPosition {
 }
 
 const getRegex = (s: string, disableRegex: boolean, caseSensitive: boolean): RegExp => {
-  return RegExp(disableRegex ? s.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&") : s, caseSensitive ? "gu" : "gui")
+  return RegExp(disableRegex ? s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') : s, caseSensitive ? "gu" : "gui");
```
Comment (sereneinserenade) [inline src/searchAndReplace.ts:57]: taken from [this comment](https://github.com/sereneinserenade/tiptap-search-and-replace/issues/4#issuecomment-1887197113)
